# Generated by Django 3.2.5 on 2021-08-08 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0002_auto_20210807_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 8, 33, 12, 496468), editable=False),
        ),
    ]
