# Generated by Django 3.2.5 on 2021-08-08 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0003_alter_internship_ad_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 8, 34, 50, 207936), editable=False),
        ),
        migrations.AlterField(
            model_name='internship_ad',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
