# Generated by Django 3.2.5 on 2021-08-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0004_alter_companyprofile_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
