# Generated by Django 3.2.5 on 2021-08-14 10:39

import Internship.internship_profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0005_alter_companyprofile_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, validators=[Internship.internship_profiles.validators.company_phone_validator_len, Internship.internship_profiles.validators.company_phone_validator_digits]),
        ),
    ]
