# Generated by Django 3.2.5 on 2021-08-03 16:25

import datetime
from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('CV', models.FileField(blank=True, upload_to='intern_cv')),
            ],
        ),
        migrations.CreateModel(
            name='Internship_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 8, 3, 19, 25, 18, 547365), editable=False)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('title', models.CharField(max_length=50)),
                ('city', models.CharField(choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Varna', 'Varna'), ('Burgas', 'Burgas'), ('Ruse', 'Ruse'), ('Stara Zagora', 'Stara Zagora'), ('Pleven', 'Pleven'), ('', '')], default='', max_length=30)),
                ('field', models.CharField(choices=[('Human Resources', 'Human Resources'), ('Information Technology', 'Information Technology'), ('Customer Service', 'Customer Service'), ('Marketing', 'Marketing'), ('SALES', 'Sales'), ('Manufacturing', 'Manufacturing'), ('Tourism', 'Tourism'), ('', '')], default='', max_length=30)),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('', '')], default='', max_length=15)),
                ('duration', models.CharField(choices=[('1 month', '1 month'), ('2 months', '2 months'), ('3 months', '3 months'), ('4 months', '4 months'), ('5 months', '5 months'), ('6 months', '6 months'), ('7 months', '7 months'), ('8 months', '8 months'), ('9 months', '9 months'), ('10 months', '10 months'), ('11 months', '11 months'), ('1 year', '1 year'), ('', '')], default='', max_length=30)),
                ('image', models.ImageField(upload_to='company')),
                ('description', django_summernote.fields.SummernoteTextField(max_length=30000)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
