# Generated by Django 3.2.5 on 2021-07-20 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('city', models.CharField(choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Varna', 'Varna'), ('Burgas', 'Burgas'), ('Ruse', 'Ruse'), ('Stara Zagora', 'Stara Zagora'), ('Pleven', 'Pleven'), ('unknown', 'unknown')], default='unknown', max_length=30)),
                ('field', models.CharField(choices=[('Human Resources', 'Human Resources'), ('Information Technology', 'Information Technology'), ('Customer Service', 'Customer Service'), ('Marketing', 'Marketing'), ('SALES', 'Sales'), ('Manufacturing', 'Manufacturing'), ('Tourism', 'Tourism'), ('unknown', 'unknown')], default='unknown', max_length=30)),
                ('duration', models.CharField(choices=[('1 month', '1 month'), ('2 months', '2 months'), ('3 months', '3 months'), ('4 months', '4 months'), ('5 months', '5 months'), ('6 months', '6 months'), ('7 months', '7 months'), ('8 months', '8 months'), ('9 months', '9 months'), ('10 months', '10 months'), ('11 months', '11 months'), ('1 year', '1 year'), ('unknown', 'unknown')], default='unknown', max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
