# Generated by Django 3.2.5 on 2021-08-03 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internship_app', '0001_initial'),
        ('internship_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_ad',
            name='applied_candidates',
            field=models.ManyToManyField(blank=True, to='internship_profiles.CandidateProfile'),
        ),
        migrations.AddField(
            model_name='internship_ad',
            name='company_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_profiles.companyprofile'),
        ),
        migrations.AddField(
            model_name='appliedtracking',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_app.internship_ad'),
        ),
        migrations.AddField(
            model_name='appliedtracking',
            name='applied_candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_profiles.candidateprofile'),
        ),
    ]
