# Generated by Django 3.2.5 on 2021-07-20 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0003_auto_20210720_1010'),
        ('internship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_profiles.companyprofile'),
        ),
    ]
