# Generated by Django 3.2.5 on 2021-08-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internship_profiles', '0001_initial'),
        ('internship_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_ad',
            name='company_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_profiles.companyprofile'),
        ),
        migrations.AddField(
            model_name='appliedtracking',
            name='applied_candidates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_profiles.candidateprofile'),
        ),
        migrations.AddField(
            model_name='appliedtracking',
            name='internship_ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_app.internship_ad'),
        ),
    ]
