# Generated by Django 3.2.5 on 2021-07-20 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internship_app', '0002_alter_internship_ad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
