# Generated by Django 3.2.5 on 2021-08-03 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship_ad',
            name='applied_candidates',
        ),
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 19, 52, 55, 794441), editable=False),
        ),
    ]
