# Generated by Django 3.2.5 on 2021-07-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0003_alter_internship_ad_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship_ad',
            name='user',
        ),
    ]
