# Generated by Django 3.2.5 on 2021-08-09 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0004_auto_20210808_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 12, 10, 5, 63923), editable=False),
        ),
    ]
