# Generated by Django 3.2.5 on 2021-07-21 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0003_auto_20210720_1010'),
        ('internship_app', '0005_internship_ad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_ad',
            name='applied_candidates',
            field=models.ManyToManyField(blank=True, to='internship_profiles.CandidateProfile'),
        ),
        migrations.AddField(
            model_name='internship_ad',
            name='company_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internship_profiles.companyprofile'),
            preserve_default=False,
        ),
    ]
