# Generated by Django 3.2.6 on 2021-08-18 08:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0006_auto_20210818_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 8, 56, 30, 638673, tzinfo=utc), editable=False),
        ),
    ]
