# Generated by Django 3.2.5 on 2021-07-21 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0006_auto_20210721_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship_ad',
            name='user',
        ),
    ]
