# Generated by Django 3.2.5 on 2021-07-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0007_remove_internship_ad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_ad',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
