# Generated by Django 3.2.5 on 2021-08-12 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0007_alter_internship_ad_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 17, 41, 57, 562385), editable=False),
        ),
    ]
