# Generated by Django 3.2.5 on 2021-07-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0008_internship_ad_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_ad',
            name='employment_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('unknown', 'unknown')], default='unknown', max_length=15),
        ),
    ]
