# Generated by Django 3.2.5 on 2021-07-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0009_internship_ad_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='city',
            field=models.CharField(choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Varna', 'Varna'), ('Burgas', 'Burgas'), ('Ruse', 'Ruse'), ('Stara Zagora', 'Stara Zagora'), ('Pleven', 'Pleven'), ('', '')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='internship_ad',
            name='duration',
            field=models.CharField(choices=[('1 month', '1 month'), ('2 months', '2 months'), ('3 months', '3 months'), ('4 months', '4 months'), ('5 months', '5 months'), ('6 months', '6 months'), ('7 months', '7 months'), ('8 months', '8 months'), ('9 months', '9 months'), ('10 months', '10 months'), ('11 months', '11 months'), ('1 year', '1 year'), ('', '')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='internship_ad',
            name='employment_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('', '')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='internship_ad',
            name='field',
            field=models.CharField(choices=[('Human Resources', 'Human Resources'), ('Information Technology', 'Information Technology'), ('Customer Service', 'Customer Service'), ('Marketing', 'Marketing'), ('SALES', 'Sales'), ('Manufacturing', 'Manufacturing'), ('Tourism', 'Tourism'), ('', '')], default='', max_length=30),
        ),
    ]
