# Generated by Django 3.2.5 on 2021-08-14 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0009_alter_internship_ad_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 13, 39, 49, 575948), editable=False),
        ),
    ]
