# Generated by Django 3.2.5 on 2021-07-25 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0009_companyprofile_is_complete'),
        ('internship_app', '0010_auto_20210725_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_of_applying', models.DateField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_app.internship_ad')),
                ('applied_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_profiles.candidateprofile')),
            ],
        ),
    ]
