# Generated by Django 3.2.6 on 2021-08-19 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0010_alter_internship_ad_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 13, 0, 21, 275839, tzinfo=utc), editable=False),
        ),
    ]
