# Generated by Django 3.2.5 on 2021-07-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0011_applieddata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppliedData',
        ),
    ]
