# Generated by Django 3.2.5 on 2021-07-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0013_appliedtracking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppliedTracking',
        ),
    ]
