# Generated by Django 3.2.6 on 2022-04-07 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0013_alter_internship_ad_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 9, 39, 7, 345146, tzinfo=utc), editable=False),
        ),
    ]
