# Generated by Django 3.2.5 on 2021-07-27 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0009_companyprofile_is_complete'),
        ('internship_app', '0014_delete_appliedtracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(editable=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_app.internship_ad')),
                ('applied_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_profiles.candidateprofile')),
            ],
        ),
    ]
