# Generated by Django 3.2.5 on 2021-07-27 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0015_appliedtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 9, 25, 3, 558763), editable=False),
        ),
        migrations.AddField(
            model_name='internship_ad',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
