# Generated by Django 3.2.5 on 2021-07-27 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0016_auto_20210727_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedtracking',
            name='CV',
            field=models.FileField(blank=True, upload_to='intern_cv'),
        ),
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 10, 0, 50, 950759), editable=False),
        ),
    ]
