# Generated by Django 3.2.5 on 2021-07-27 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0017_auto_20210727_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedtracking',
            name='applied_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 10, 12, 54, 23820), editable=False),
        ),
    ]
