# Generated by Django 3.2.5 on 2021-07-28 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0018_auto_20210727_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedtracking',
            name='CV',
            field=models.FileField(upload_to='intern_cv'),
        ),
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 17, 16, 6, 130303), editable=False),
        ),
    ]
