# Generated by Django 3.2.5 on 2021-07-28 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0019_auto_20210728_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 17, 35, 11, 362067), editable=False),
        ),
    ]
