# Generated by Django 3.2.5 on 2021-07-29 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0023_alter_internship_ad_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedtracking',
            name='CV',
            field=models.FileField(blank=True, upload_to='intern_cv'),
        ),
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 12, 27, 47, 19202), editable=False),
        ),
    ]
