# Generated by Django 3.2.5 on 2021-07-29 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0024_auto_20210729_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 19, 23, 2, 931986), editable=False),
        ),
        migrations.AlterField(
            model_name='internship_ad',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
