# Generated by Django 3.2.5 on 2021-07-31 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0025_auto_20210729_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 7, 19, 40, 609352), editable=False),
        ),
    ]
