# Generated by Django 3.2.5 on 2021-07-31 05:42

import datetime
from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0026_alter_internship_ad_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 8, 42, 35, 827967), editable=False),
        ),
        migrations.AlterField(
            model_name='internship_ad',
            name='description',
            field=django_summernote.fields.SummernoteTextField(max_length=2000),
        ),
    ]
