# Generated by Django 3.2.5 on 2021-07-31 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0027_auto_20210731_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 9, 1, 23, 657783), editable=False),
        ),
        migrations.AlterField(
            model_name='internship_ad',
            name='image',
            field=models.ImageField(upload_to='company'),
        ),
    ]
