# Generated by Django 3.2.5 on 2021-07-31 06:13

import datetime
from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0028_auto_20210731_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 9, 13, 53, 802379), editable=False),
        ),
        migrations.AlterField(
            model_name='internship_ad',
            name='description',
            field=django_summernote.fields.SummernoteTextField(max_length=30000),
        ),
    ]
