# Generated by Django 3.2.5 on 2021-07-31 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0029_auto_20210731_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_ad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 19, 44, 28, 583410), editable=False),
        ),
    ]
