# Generated by Django 3.2.5 on 2021-07-19 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internship_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('profile_image', models.ImageField(blank=True, upload_to='intern_profile')),
                ('CV', models.FileField(blank=True, upload_to='intern_cv')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='internship_auth.internshipuser')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('company_name', models.CharField(blank=True, max_length=35)),
                ('company_logo', models.ImageField(blank=True, upload_to='company_logo')),
                ('description', models.ImageField(blank=True, max_length=500, upload_to='')),
                ('company_image', models.ImageField(blank=True, upload_to='company_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='internship_auth.internshipuser')),
            ],
        ),
    ]
