# Generated by Django 3.2.5 on 2021-07-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='profile',
            field=models.CharField(default='Candidate', max_length=10),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='profile',
            field=models.CharField(default='Company', max_length=10),
        ),
    ]
