# Generated by Django 3.2.5 on 2021-07-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0002_auto_20210720_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='profile',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
