# Generated by Django 3.2.5 on 2021-07-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0003_auto_20210720_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
