# Generated by Django 3.2.5 on 2021-07-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0004_alter_companyprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_image',
            field=models.ImageField(default='media/InitialProfilePics/pic.png', upload_to='intern_profile'),
        ),
    ]
