# Generated by Django 3.2.5 on 2021-07-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0005_alter_candidateprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_image',
            field=models.ImageField(default='InitialProfilePics/pic.png', upload_to='intern_profile'),
        ),
    ]
