# Generated by Django 3.2.5 on 2021-07-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0006_alter_candidateprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_image',
            field=models.ImageField(default='InitialProfilePics/company_pic.png', upload_to='company_pics'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(default='InitialProfilePics/logo.png', upload_to='company_logo'),
        ),
    ]
