# Generated by Django 3.2.5 on 2021-07-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0008_candidateprofile_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
