# Generated by Django 3.2.5 on 2021-07-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0010_alter_companyprofile_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_image',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(default='InitialProfilePics/Logo.jpg', upload_to='company_logo'),
        ),
    ]
