# Generated by Django 3.2.5 on 2021-07-28 14:47

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0011_auto_20210728_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_address',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_website',
            field=models.URLField(blank=True),
        ),
    ]
