# Generated by Django 3.2.5 on 2021-07-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0012_auto_20210728_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(default='img/Logo.jpg', upload_to='company_logo'),
        ),
    ]
