# Generated by Django 3.2.5 on 2021-08-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0015_alter_companyprofile_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
    ]
