# Generated by Django 3.2.5 on 2021-08-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_profiles', '0016_alter_companyprofile_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
