# Generated by Django 3.2.5 on 2021-07-29 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship_auth', '0003_alter_internshipuser_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipuser',
            name='company_name',
        ),
    ]
